In [23]:
import numpy as np

In [24]:
time = np.arange(0,27000,1)
time



array([    0,     1,     2, ..., 26997, 26998, 26999])

In [25]:
flux = np.random.rand(27000)
len(flux)

27000

In [30]:
time1 = time.reshape(-1, 10)
flux1 = flux.reshape(-1, 10)

time1.shape

(2700, 10)

In [27]:
time_binned = time1.mean(axis=-1)
flux_binned = flux1.mean(axis=-1)

In [32]:
def binning_data(time, flux, bin_size):
    times = time.reshape(-1, bin_size)
    fluxes = flux.reshape(-1, bin_size)

    time_binned = times.mean(axis=-1)
    flux_binned = fluxes.mean(axis=-1)

    return time_binned, flux_binned


In [34]:
time, flux = binning_data(np.linspace(0,100, 100000), np.random.rand(100000), 10)
time, flux

(array([4.50004500e-03, 1.45001450e-02, 2.45002450e-02, ...,
        9.99754998e+01, 9.99854999e+01, 9.99955000e+01]),
 array([0.52011609, 0.46921359, 0.5666599 , ..., 0.47079031, 0.7371442 ,
        0.46308736]))